config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  resources :users
  resources :questions do
    resources :answers, only: [:create, :destroy, :edit, :update] do
      resources :comments, only: [:create, :destroy] do
        resources :votes, only: [:create,:update]
      end
      resources :votes, only: [:create,:update]
    end
    resources :comments, only: [:create, :destroy] do
      resources :votes, only: [:create,:update]
    end
    resources :votes, only: [:create,:update]
  end

  resources :tags, only: [:create, :destroy, :index, :show]

  get '/login' => 'session#new'
  resources :session, only: [:create, :destroy]

end

app/models/answer.rb
class Answer < ActiveRecord::Base

has_many :comments, as: :commentable, dependent: :destroy
has_many :votes, as: :votable, dependent: :destroy

belongs_to :user
belongs_to :question

validates :content, :user_id, :question_id, presence: true


  def score
    self.votes.pluck(:value).reduce(:+) || 0
  end


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @question = Question.find(params[:id])
    @answer = @question.answers.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params)
    @answer.user_id = current_user.id
    if @answer.save
      redirect_to "/questions/#{@answer.question.id}"
    else
      flash[:alert] = @answer.errors.full_messages
      render 'new'
  end
end

  def edit
    @answer = Answer.find(params[:id])
    @question = Question.find(params[:question_id])

  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update_attributes(answer_params)
      redirect_to "/questions/#{@answer.question.id}"
    else
      flash[:alert] = @answer.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @answer = Answer.find(params[:id]).destroy
    flash[:success] = "Answer Deleted"
    redirect_to :back
  end

  private

  def answer_params
    params.require(:answer).permit(:content)
  end


end

app/views/answers/_answer.html.erb
<div>
	<div>
		<%= answer.content %><br>
		--<%= answer.user.username %>
		<%= answer.score %>
	</div>

	<% if current_user.hasnt_voted?("Answer", answer.id) %>
		<%= form_for [@question,answer,@vote], html: {class: 'upvote'} do |f|%>
			<%= f.hidden_field :value %>
			<%= hidden_field_tag 'value', 1 %>
			<%= hidden_field_tag 'vote_type', "answer" %>
			<%= f.submit "" %>
		<%end %>
		<%= form_for [@question,answer,@vote] do |f|%>
			<%= f.hidden_field :value %>
			<%= hidden_field_tag 'value', -1 %>
			<%= hidden_field_tag 'vote_type', "answer" %>
			<%= f.submit "" %>
		<%end %>
	<% end %>

	<ul>
		<% answer.comments.each do |comment| %>
			<li>
				<%= comment.content %><br>
				<%= comment.user.username %>
			</li>
			<%= comment.score %>
			<% if current_user.hasnt_voted?("Comment", comment.id) %>
				<%= form_for [@question ,answer, comment,@vote], html: {class: 'upvote'} do |f|%>
					<%= f.hidden_field :value %>
					<%= hidden_field_tag 'value', 1 %>
					<%= hidden_field_tag 'vote_type', "comment" %>
					<%= f.submit "" %>
				<%end %>
			<%end %>
			<%= form_for [@question,comment,@vote] do |f|%>
				<%= f.hidden_field :value %>
				<%= hidden_field_tag 'value', -1 %>
				<%= hidden_field_tag 'vote_type', "comment" %>
				<%= f.submit "" %>
			<% end %>
		<% end %>
	</ul>

	<div>
		<%= button_tag 'comment', class: 'answer_comment_button'%>
		<%= form_for [@question, answer, @comment], html: {class:'answer_comment_form', id: 'answer_comment_form'} do |f|%>
			<%= hidden_field_tag :comment_type, 'Answer'  %>
			<%= f.text_area :content %><br>
			<%= f.submit 'submit' %>
		<% end %>
	</div>
	<%= button_to "Delete This Answer", question_answer_path(@question.id, answer.id), method: :delete, confirm: "shaqfu" %>
</div>
<br>

<hr>

app/views/answers/edit.html.erb
Edit your answer, make it hateful so all those people who upvoted it look like dicks

<%= form_for [@question,@answer] do |f|%>
<%= f.label :content %>
<%= f.text_area :content, value: @answer.content %>
<%= f.submit 'submit' %>
<% end %>