config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  resources :users
  resources :questions do
    resources :answers, only: [:create, :destroy, :edit, :update] do
      resources :comments, only: [:create, :destroy] do
        resources :votes, only: [:create,:update]
      end
      resources :votes, only: [:create,:update]
    end
    resources :comments, only: [:create, :destroy] do
      resources :votes, only: [:create,:update]
    end
    resources :votes, only: [:create,:update]
  end

  resources :tags, only: [:create, :destroy, :index, :show]

  get '/login' => 'session#new'
  resources :session, only: [:create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShaqOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <nav>
      <ul>
        <li><%= link_to 'home', root_path%></li>
        <li><%= link_to 'ask a question', new_question_path %></li>
        <% if current_user %>
        <li><%= link_to 'logout', session_path(current_user.id), method: :delete %></li>
        <li><%= link_to "#{current_user.username}", current_user %></li>
        <% else %>
        <li><%= render 'session/new' %></li>
        <li><%= link_to 'sign up', new_user_path %></li>
        <% end %>
      </ul>
    </nav>
  </header>
<% if flash %>
  <% flash.each do |name, message| %>
    <div><%= message %></div>
  <% end %>
<% end %>
<%= yield %>

</body>
</html>